### PR TITLE
docs: fix pip install command for strawberry and Robyn

### LINKED ISSUE #678: Missing pip install commands for strawberry and Robyn
### Bug Description

Comment in #676

### Steps to Reproduce

The issue is in this section: https://robyn.tech/documentation/api_reference/graphql-support#step-2-activate-the-virtualenv-and-install-robyn

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by jeasoft**
This is a quick fix for the command line for the installation of Robyn and Strawberry in the docs

**Description**

Fixing pip install command for Strawberry GraphQL and Robyn

This PR fixes #678

### CODE REVIEW

**Review by Mr-Sunglasses — APPROVED** [review]
Thanks a lot @jeasoft ✨, Awesome work

**Comment by Mr-Sunglasses** [comment]
@jeasoft Could you please open an issue for this PR and link this PR to that issue 😄

**Comment by jeasoft** [comment]
Done (#678) and updated in the first comment. Thank you guys!

**Review by sansyrox — APPROVED** [review]
LGTM! 🔥 ✨ 

Thank you @jeasoft and @Mr-Sunglasses

**Pull request merged**
