### PR TITLE
ci: use nox

### LINKED ISSUE #576: Add tox or other tools to automate and standardize testing
##  Problem I Faced 🥺
While working on #558 😅, I faced the challenge that testing all the `integration_tests` requires either running each test individually or relying solely on Github actions, which run after pushing commits. Unfortunately, the latter option can be quite annoying 🙄 due to the considerable time it takes. As a result, I strongly felt the need for a tool like tox 🚀, which would enable me to run all test cases with just one simple command `tox`.

## The Benefits we get after using these tools:- 

- Easily runs all the tests locally.
- checking your package builds and installs correctly under different environments (such as different Python implementations, versions or installation dependencies).
- running your tests in each of the environments with the test tool of choice.
- acting as a frontend to continuous integration servers, greatly reducing boilerplate and merging CI and shell-based testing.
- Overall it enhances the dev experience.
### IMO we can go ahead with these two tools: [tox](https://tox.wiki/en/4.6.4/) or [nox](https://nox.thea.codes/en/stable/)

@sansyrox What do you think about it 😃 .

### PR DESCRIPTION
**Pull request by IdoKendo**
**Description**

This PR fixes #576 by using tox in the python CI.

This means that you can also locally run `tox` and get the same result as in the CI, making local testing simpler and more similar to the way CI works.

Note that you will still need to have all python runtimes in your local machine, as tox relies on them.

### CODE REVIEW

**Comment by sansyrox** [comment]
Hey @IdoKendo :wave: 

Thank you for the PR :smile: I have one question - will `pytest integration_tests` still work properly? If I want to do a quick test

**Comment by IdoKendo** [comment]
Yeah, tox runs pytest behind the scenes so it's all the same if you hust want to use pytest for a quick run

**Comment by IdoKendo** [comment]
Seems that building maturin with tox is yet unsupported, looking into it.

**Comment by IdoKendo** [comment]
Hey @sansyrox 👋 
Since it seems that tox and maturin don't play well together, I decided to use nox - it's actually even nicer and makes local testing and ci have even better parity. This PR is ready for review 🚀

**Comment by sansyrox** [comment]
Hey @IdoKendo 👋 

How would one go about using `nox` locally? What command do you usually use?

**Comment by IdoKendo** [comment]
Hey @sansyrox 👋 
You can either run `nox` to run the complete suite - or if you want to run just a specific version you can run `nox -p 3.11` for example for python 3.11, and of course you can still run `pytest` normally 😃

**Comment by IdoKendo** [comment]
Hey @sansyrox 👋  Just pinging to remind you of this PR, any more queries before it's approved?

**Comment by sansyrox** [comment]
Hey @IdoKendo 👋 

Nothing specific. I just want to try running this on my machine. However, I am at Python conference right now. I will complete the review by this weekend 😅

**Review by sansyrox — APPROVED** [review]
Hey @IdoKendo 👋 

Great work! Thank you 😄 

LGTM 🔥 ✨

**Pull request merged**
