### PR TITLE
feat: sidebar hide

### LINKED ISSUE #903: website: navgation drawer hide
can we have a way to hide the navigation drawwer?

### PR DESCRIPTION
**Pull request by VishnuSanal**
## Description

This PR fixes #903

## Summary

This PR does....

## PR Checklist

Please ensure that:

- [x] The PR contains a descriptive title
- [ ] The PR contains a descriptive summary of the changes
- [x] You build and test your changes before submitting a PR.
- [ ] You have added relevant documentation
- [ ] You have added relevant tests. We prefer integration tests wherever possible

## Pre-Commit Instructions:

- [ ] Ensure that you have run the [pre-commit hooks](https://github.com/sansyrox/robyn#%EF%B8%8F-to-develop-locally) on your PR.

### CODE REVIEW

**Comment by VishnuSanal** [comment]
current issues:

- [ ] the button position
- [ ] contents under the nav bar container cannot be clicked when the nav bar is hidden

**Comment by VishnuSanal** [comment]
this is ready for review: @sansyrox PTAL. :)

**Comment by sansyrox** [comment]
@VishnuSanal , please follow the PR checklist 😄 

> PR Checklist
Please ensure that:

 The PR contains a descriptive title
 The PR contains a descriptive summary of the changes
 You build and test your changes before submitting a PR.
 You have added relevant documentation
 You have added relevant tests. We prefer integration tests wherever possible

**Comment by sansyrox** [comment]
Screenshot 2024-08-03 at 15 14 06


Hey @VishnuSanal , this PR breaks the responsiveness on mobile. Could you have a look ?

**Comment by VishnuSanal** [comment]
Wait, what?! We already had a button to hide the sidebar on mobile? :O

**Pull request closed without merging**
