### PR TITLE
Replace `body` attribute in Response Object in the docs

### PR DESCRIPTION
**Pull request by carlosm27**
**Description**
This PR replace the `body` attribute for `description` attribute in the section relate to the Response object in the documentation.

This PR fixes #

### CODE REVIEW

**Comment by IdoKendo** [comment]
Hey @carlosm27 👋 I think you can update the docs in the same PR as updating the syntax (#580), there's no need for separating the code and docs in two PRs.

**Comment by carlosm27** [comment]
Hey @sansyrox, sorry, my bad. Thank you for tell me.

**Comment by sansyrox** [comment]
Thanks @carlosm27 for the tag. But I think you mean @IdoKendo 😉

**Comment by sansyrox** [comment]
Hey @carlosm27 👋 

I have moved your commit to your other PR 😄 We can safely close this.

**Pull request closed without merging**
