### PR TITLE
Add default None to QueryParams get fn

### LINKED ISSUE #763: query_params.get("param_name") requires a default value
### Bug Description

query_params.get("param_name") requires a default value

this default value should be optional and not manadataed

### Steps to Reproduce

_No response_

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by StandinKP**
**Description**

This PR fixes #763

### CODE REVIEW

**Comment by StandinKP** [comment]
I am now matching the default as well to return either None or the default value. So if you don't pass the default param it will return the None. I can try to add a test case if we have some for testing the query params. I can see test_get_request and other similar tests. Do you want me to add it there?

**Comment by sansyrox** [comment]
> I am now matching the default as well to return either None or the default value. So if you don't pass the default param it will return the None. I can try to add a test case if we have some for testing the query params. I can see test_get_request and other similar tests. Do you want me to add it there?

Yes, please do try it with test cases. As both of the diffs are doing the same things. Do give it a thought, if it still doesn't make a lot of sense then I will be happy to explain :D

**Comment by StandinKP** [comment]
> Yes, please do try it with test cases. As both of the diffs are doing the same things. Do give it a thought, if it still doesn't make a lot of sense then I will be happy to explain :D

I just checked and you are right both of them do the same output. Both of them return None if we don't pass in the default value. So I have a question what exactly is wrong with the current setup?

**Comment by sansyrox** [comment]
See this - https://github.com/sparckles/Robyn/pull/787

**Comment by sansyrox** [comment]
Closing this, as it has been fixed.

**Pull request closed without merging**
