### PR TITLE
feat: Add OpenAPI middleware with comprehensive update_info 

### PR DESCRIPTION
**Pull request by tavallaie**
### Summary
To solve #247 
This pull request introduces the OpenAPI middleware with a comprehensive `update_info` method that allows dynamic updates to the OpenAPI specification. It includes the following changes:

1. **OpenAPI Middleware**: A new `OpenAPIMiddleware` class that handles CRUD operations and dynamically updates the OpenAPI specification.
2. **Comprehensive OpenAPI Info**: Uses dataclasses to manage OpenAPI Info, Contact, License, Server, External Documentation, and Components.
3. **Unit Tests**: Adds unit tests for the `update_info` method to ensure that the OpenAPI info is updated correctly.

### Changes

- Added `openapi_middleware.py` to manage OpenAPI specifications.
- Updated `__init__.py` to include the middleware.
- Added `unit_tests/test_openapi_middleware.py` with unit tests for the middleware.

### Testing

Run the unit tests to ensure everything works correctly:

```sh
PYTHONPATH=.. python -m unittest unit_tests/test_openapi_middleware.py

### CODE REVIEW

**Comment by tavallaie** [comment]
I don't know why CI failed, but I added other methods like adding middleware and Data Class. I didn't see #890 before my commit, my bad. but I think the data class approach is much cleaner. but not sure about other things. I would like to see the comparison and discuss the advantages of both.

**Comment by sansyrox** [comment]
Hey @tavallaie 👋 

Thank you for the PR 😄 But one of our community members is already working on https://github.com/sparckles/Robyn/pull/890 . I don't want any clashes to happen 😅 

Could you help me review that PR instead? I will be happy to add you as a co-author there (using https://github.com/sansyrox/git-add-co-author)

**Comment by sansyrox** [comment]
@tavallaie 

>  but I think the data class approach is much cleaner. 

I agree with this, and I have borrowed your approach and left a review there.

**Comment by tavallaie** [comment]
I mentioned myself in #890 to let you know that there is another approach, and we can make the best of two, so feel free to use it as it is well suited.
For co-authors, what should I do?

**Comment by sansyrox** [comment]
@tavallaie , you don't need to do a lot :D Just help with a review on 890. I'll add you as a co-author before merging :)

**Comment by sansyrox** [comment]
The PR is merged now 😄

**Pull request closed without merging**
