### PR TITLE
Description parameter

### LINKED ISSUE #552: Replace the `body` parameter in the response with a `description` parameter
Response body makes little sense. I think `description`/`message` makes more sense.

### PR DESCRIPTION
**Pull request by carlosm27**
**Description**
This replace the `body` parameter in the `response` object for `description` parameter.

This PR fixes #552

### CODE REVIEW

**Comment by sansyrox** [comment]
Hey @carlosm27 👋 

Thank you for the PR. I will have a proper look tomorrow 😄

**Review by sansyrox — COMMENTED** [review]
Great work @carlosm27 👋 

All looks good at first glance. Will compare the diffs before merging tomorrow 😄

**Comment by sansyrox** [comment]
Hey @carlosm27 👋 

Great work on this PR 😄  All looks good. Can you please update the documentation in the docs folder and the docs website please?

**Comment by carlosm27** [comment]
Hey @sansyrox, thank you. Yes, I will update the documentation.

**Review by sansyrox — APPROVED** [review]
LGTM 🔥

**Pull request merged**
