### PR TITLE
Open api spec support and swagger docs

### LINKED ISSUE #247: [Feature Request] Add openapi integration
**Current Behavior**

Robyn doesn't generate [OpenAPI](https://swagger.io/specification/) documentations by default. OpenAPI integration is a highly demanded feature and I am super keen on supporting it.

**Desired Behavior**

A few good links to have a look at are:

- https://github.com/marshmallow-code/apispec
- https://github.com/tiangolo/fastapi/blob/bcabbf8b37db3fbc020560e94ad2f90e64d1510a/fastapi/openapi/docs.py#L1

A high level way of implementing the feature would require:
- Adding a `documentation` route(r)
- Make it configurable
- Make it adhere to the passed params `--dev/--prod`
- Create a class that has OpenAPI pre-requisites (pre-populating-html strings, reponse_parser, etc.)
- Pass it to the threadpool.

### PR DESCRIPTION
**Pull request by Mr-Sunglasses**
**Description**

This PR fixes #247 

Working on the Most Awaited feature. 

image

### CODE REVIEW

**Comment by sansyrox** [comment]
Hey @Mr-Sunglasses 👋 

How are we looking here? Can we help you with something?

**Comment by sansyrox** [comment]
Any updates on this @Mr-Sunglasses ?

**Comment by Mr-Sunglasses** [comment]
> Any updates on this @Mr-Sunglasses ?

Yess, forgot to push the changes........

**Comment by jeasoft** [comment]
Hey, can you add an example of how to use this in the docs? Should be nice also to have it there.

**Comment by sansyrox** [comment]
Hey @jeasoft 👋 

This feature is not ready yet :( . I will have a look at it next week if it is not ready by then 😄

**Comment by jeasoft** [comment]
Cool cool!

**Comment by justin13888** [comment]
Is this PR still being worked on or put on hold?

**Comment by sansyrox** [comment]
Hey @justin13888 ,



We tried a different approach here - https://github.com/sparckles/Robyn/pull/742. 



But we will finalise the PR merge by July 😄 



It will most likely be a separate PR

**Comment by sansyrox** [comment]
Agreed. Closing.

**Pull request closed without merging**
